### PR TITLE
provider: removal of ``expires`` update

### PR DESCRIPTION
**Pull request by drjova**
Signed-off-by: Harris Tzovanakis <me@drjova.com>

### CODE REVIEW

**Comment by drjova** [comment]
@slint any idea about the lowest requirement error? 😕

**Comment by drjova** [comment]
@slint ok is passing now, should I add a release commit as well?

**Comment by slint** [comment]
LGTM for a release, I'm a bit cautious about the version though. On one hand, this is wrong behavior currently, since the documentation itself says that the personal token shouldn't expire:

https://github.com/inveniosoftware/invenio-oauth2server/blob/e3515a9d35f01ddae8fa27d2851ef18c80d96bdc/invenio_oauth2server/models.py#L396 

I would go with a patch version, i.e. `v1.0.4`, since e.g. we're seeing this issue affecting some users on Zenodo as well now (they get a "token expired" error message though)... WDYT @lnielsen, @ntarocco ?

**Comment by ntarocco** [comment]
> LGTM for a release, I'm a bit cautious about the version though. On one hand, this is wrong behavior currently, since the documentation itself says that the personal token shouldn't expire:
> 
> https://github.com/inveniosoftware/invenio-oauth2server/blob/e3515a9d35f01ddae8fa27d2851ef18c80d96bdc/invenio_oauth2server/models.py#L396
> 
> I would go with a patch version, i.e. `v1.0.4`, since e.g. we're seeing this issue affecting some users on Zenodo as well now (they get a "token expired" error message though)... WDYT @lnielsen, @ntarocco ?

Agree, especially given that tokens can be revoked. GitHub tokens work in the same way, no expiration.
But then, it looks like you can completely remove the config `OAUTH2_PROVIDER_TOKEN_EXPIRES_IN` and related tests...

**Comment by drjova** [comment]
updated

**Comment by drjova** [comment]
@slint updated :)

**Comment by slint** [comment]
Also pushed the tag, so just waiting [for Travis](https://travis-ci.org/inveniosoftware/invenio-oauth2server/builds/621490507) now for the PyPI release

**Comment by drjova** [comment]
thanks 🥇

**Pull request merged**
