### PR TITLE
global: Flask-WTF upgrade to 0.13

### LINKED ISSUE #82: installation: incompatibility between flask-wtf and wtforms-alchemy
Flask-WTF-0.13 seems incompatible with wtforms-alchemy-0.16.1 and crashes invenio-oauth2server:

````
 File "/home/travis/virtualenv/python3.3.5/lib/python3.3/site-packages/invenio_oauth2server/views/__init__.py", line 30, in <module>
    from .settings import blueprint as settings_blueprint
  File "/home/travis/virtualenv/python3.3.5/lib/python3.3/site-packages/invenio_oauth2server/views/settings.py", line 35, in <module>
    from ..forms import ClientForm, TokenForm
  File "/home/travis/virtualenv/python3.3.5/lib/python3.3/site-packages/invenio_oauth2server/forms.py", line 117, in <module>
    class ClientFormBase(model_form_factory(Form)):
  File "/home/travis/virtualenv/python3.3.5/lib/python3.3/site-packages/wtforms_alchemy/__init__.py", line 140, in model_form_factory
    class ModelForm(six.with_metaclass(meta, base)):
  File "/home/travis/virtualenv/python3.3.5/lib/python3.3/site-packages/six.py", line 808, in __new__
    return meta(name, bases, d)
TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases
````

This problem showed up when upgrading from Flask-WTF-0.12 to Flask-WTF-0.13

### PR DESCRIPTION
**Pull request by hachreak**
* Updates forms to support Flask-WTF>=0.13. (Closes #82)

Signed-off-by: Leonardo Rossi <leonardo.r@cern.ch>

### CODE REVIEW

**Comment by hachreak** [comment]
ping @drjova

**Comment by jirikuncar** [comment]
@hachreak `s/Closes/closes/` + can you wait for new release of Invenio-Accounts?

**Comment by hachreak** [comment]
@jirikuncar  I changed the `Closes` :+1:

**Comment by jirikuncar** [comment]
@hachreak see https://pypi.python.org/pypi/invenio-accounts/1.0.0a15

**Comment by hachreak** [comment]
I updated the `invenio-accounts` requirements. 
It's ok like this? :smile:

**Comment by jirikuncar** [comment]
@hachreak yes 👍  let's see travis.

**Pull request merged**
