### PR TITLE
templates: authorize redesign

### LINKED ISSUE #140: ui: clarify who is the logged in user and who is the author of application in authorization request form
Currently authorization request form might not highlight enough who is the logged in user / identity, i.e. whose resources the application is requesting authorization.

Possibly the application name and author of application should also be highlighted more. 

Current invenio-oauth2server authorization request form looks like this:

authorization_request_form

For inspiration, here is how GitHub and Google have done their OAuth application authorization request forms:

authorization_request_form_google

authorization_request_form_github

### PR DESCRIPTION
**Pull request by switowski**
* Redesigns the "Authorize application" page to be more clear on who is
  the currently logged in user (closes #140).

### CODE REVIEW

**Comment by switowski** [comment]
oauth2

**Comment by switowski** [comment]
Here is the updated version after rebasing:

oauth3

**Comment by lnielsen** [comment]
I must admit I prefer the old layout shown in #149

**Comment by switowski** [comment]
Ok, I will revert it and just add the currently logged-in user email to the text.

**Comment by switowski** [comment]
Latest version:
oauth4

**Pull request merged**
