### PR TITLE
packaging: use flask-security-fork

### PR DESCRIPTION
**Pull request by david-caro**
Signed-off-by: David Caro <david@dcaro.es>

### CODE REVIEW

**Comment by omelkonian** [comment]
@david-caro Could you please also close #92, by adding `(closes #92)` in the commit message?

**Comment by david-caro** [comment]
done

**Comment by omelkonian** [comment]
Please replace the reference from #93 to #92.

**Comment by david-caro** [comment]
Dammit :dancer: I saw the #93 reference in the history... on it

**Comment by jirikuncar** [comment]
@david-caro if you look to `git log` you will see that don't use `packaging:` component. Please find the most suitable one based on the history. Thank you!

**Comment by jirikuncar** [comment]
After talking with @lnielsen we should remove the Flask-Security(-Fork) dependency and imports if possible.

**Comment by david-caro** [comment]
Should that be done in this pull request? Looks like a drastic change.

**Comment by jirikuncar** [comment]
It looks quite straightforward except `tests/helpers.py`. See https://github.com/inveniosoftware/flask-security-fork/blob/master/flask_security/decorators.py#L17

**Comment by lnielsen** [comment]
@david-caro The reason to remove the dependency is so that we won't have to cascade changes again if Invenio-Accounts's dependency is changed back to Flask-Security (likely possible since the guy is looking for new maintainers for the package). I.e. a bit of extra work now would save as all for headache on the next update. It's much appreciated if you can apply the fixes:

```
$ git grep flask_security
invenio_oauth2server/decorators.py:from flask_security import current_user
invenio_oauth2server/ext.py:from flask_security import current_user
invenio_oauth2server/views/server.py:from flask_security import login_required
tests/helpers.py:from flask_security import url_for_security
tests/test_decorators.py:from flask_security import url_for_security
```
Following changes should do the job:
``flask_security import current_user -> from flask_login import current_user``
``flask_security import url_for_security -> from flask import url_for + url_for('security.<view>')``

**Comment by david-caro** [comment]
@lnielsen thanks for the explanation, what about `login_required` one?

**Comment by david-caro** [comment]
Should I use this one instead? https://flask-login.readthedocs.io/en/latest/#flask_login.login_required

**Comment by lnielsen** [comment]
Thanks a lot. Yep like this: ``flask_security import login_required -> from flask_login import login_required``

**Comment by krzysztof** [comment]
Is this ready for merging?

**Comment by david-caro** [comment]
On my side yes, not sure if @lnielsen  or @jirikuncar have any more comments.

**Comment by lnielsen** [comment]
LGTM

**Comment by david-caro** [comment]
Wait, this is not the last commit, it's missing the removal of the url_for_security, pushing now (sorry for the confusion)

**Comment by jirikuncar** [comment]
@david-caro `* Remove Flask-Security` -> `* Removes Flask-Security`

**Comment by david-caro** [comment]
@jirikuncar I though we had to use the imperative tense for the description... will take note.

**Pull request merged**
